config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check
  root to: "stations#index"

  resources :stations, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    resources :bookings, only: [:create]
  end

  resources :users, only: [:show, :update] do
    resources :vehicles, only: [:new, :create, :edit, :update] # Ressources des véhicules
  end

  get '/leaderboard', to: 'users#leaderboard'
  resources :vehicles, only: [:edit, :update, :destroy, :new, :create]

  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do

    resources :conflicts, only: [:new, :create]
    resources :messages, only: [:create] # Ressource des messages
    member do
      patch :submit_offer
      patch :accept_offer
      patch :reject_offer
      patch :start_charge
      patch :stop_charge
      patch :validate_payment
    end
  end

  resources :vehicles do
    get 'get_models_by_brand', on: :collection
  end


  resources :badges, only: [:create, :destroy]

  get '/wheel', to: 'wheels#index'

  post '/start_reservation', to: 'reservations#start_reservation'
  post '/accept_offer', to: 'reservations#accept_offer'
  post '/reject_offer', to: 'reservations#reject_offer'
  post '/start_charging', to: 'reservations#start_charging'
  post '/stop_charging', to: 'reservations#stop_charging'

end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :user
  # has_one :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :address, presence: true
  validates :plug, presence: true
  validates :brand, presence: true
  validates :model, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action do
    current_user.badges.each do |badge|
      if badge.duration < Time.now
        badge.destroy
      end
      if badge.name == "minus_one_euro" && badge.created_at == "1999-12-31 23:00:00"
        badge.destroy
      end
    end
  end

  def index

    redirect_to new_vehicle_path if current_user.vehicles.length < 1

    @vehicles = current_user.vehicles

    @array_of_cars = []
    @vehicles.each do |vehicle|
      arr = []
      arr.push(" " + vehicle.brand + " " + vehicle.model + " - " + vehicle.plug + " ")
      arr.push(vehicle.id)
      @array_of_cars.push(arr)
    end

      if params[:address] && params[:plug] && params[:date_available]
        @stations = Station.near(params[:address], 10, order: :distance).where('user_id <> ? AND plug = ? AND available = ? AND ( avaibility_end IS NULL OR avaibility_end < ? )',current_user.id, Vehicle.find(params[:plug]).plug, 'true', params[:date_available].to_time)
        # @stations = Station.all
      else
        @stations = ""
      end
    # wip ci dessous
    if @stations != ""
      @markers = @stations.geocoded.map do |station|
        {
          lat: station.latitude,
          lng: station.longitude,
          niv: station.user.xp,
          marker_html: render_to_string(partial: "marker"),
          marker_html_2: render_to_string(partial: "marker_2"),
          marker_html_3: render_to_string(partial: "marker_3"),
          marker_html_4: render_to_string(partial: "marker_4"),
          info_window_html: render_to_string(partial: "info_window", locals: {station: station})
        }
      end
      location = Geocoder.search(params[:address])[0]
      @markers.push({lat: location.latitude, lng: location.longitude, bs: "true", marker_html_5: render_to_string(partial: "marker_5") }) if location
    else
      @markers = [];
    end

    @booking = Booking.new
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    @station.user = current_user

    if @station.save
      redirect_to user_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    Station.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end

  private

  def station_params
    params.require(:station).permit(:address, :plug, :brand, :model, :max_kW_recharge, :available, :availability_end, :code_station, :latitude, :longitude, :photo)
  end



end

app/views/stations/_info_window.html.erb
<div class="the-popup-map"><%= station.user.username.capitalize %></div>

app/views/stations/_marker.html.erb
<%= image_tag Badge.m[0], height: 30, width: 30, alt: "Logo" %>

app/views/stations/_marker_2.html.erb
<%= image_tag Badge.m[1], height: 30, width: 30, alt: "Logo" %>

app/views/stations/_marker_3.html.erb
<%= image_tag Badge.m[2], height: 30, width: 30, alt: "Logo" %>

app/views/stations/_marker_4.html.erb
<%= image_tag Badge.m[3], height: 30, width: 30, alt: "Logo" %>

app/views/stations/_marker_5.html.erb
<%= image_tag Badge.m[4], height: 30, width: 30, alt: "Logo" %>

app/views/stations/index.html.erb
<div class="container-sm">
  <div class="station-main-titre mt-2">Recharger ma voiture</div>
  <div class="row">

  <% if params[:address] %>
  <% params[:address] != "" ? placeholder = params[:address] : placeholder = "Adresse..."%>
  <% else %>
  <% placeholder = "Adresse ..." %>
  <% end %>

    <%# Ci dessous formulaire d'envois des parametres de filtre %>
    <% params[:plug] ? the_selected = params[:plug] : the_selected = "1" %>
  <%= form_with url: stations_path, method: :get, class: "" do |f|%>
      <div class="d-flex justify-content-start"><%= f.select :plug, options_for_select(@array_of_cars, :selected => the_selected ) %></div>
      <div class="station-main-titre secondaire mt-2">Quand ?</div>
      <%= f.datetime_field :date_available, class: 'form-control formulaire' %>
        <div class="station-main-titre secondaire mt-2">Ou ?</div>
      <div class="d-flex w-100 form-control justify-content-between mb-2 formulaire">
      <%= f.text_field :address,
      placeholder: placeholder, class: 'barre-de-recherche' %>
      <%= f.button nil, class: "barre-de-recherche" do %><i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
      </div>
    <% end %>

  </div>
  <%# ci dessous MapBox %>
  <div  class="mt-2 carte-radius-border" style="width: 100%; aspect-ratio: 1/1;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  <%# ligne de coupure grise %>


  <%# espace %>
  <div class="station-break"></div>

  <%# variable price %>
  <% if params[:plug] %>
  <% capacite_batterie = Vehicle.car_list[Vehicle.find(params[:plug]).brand]['capacite'] %>
  <% puissance_maximale = Vehicle.car_list[Vehicle.find(params[:plug]).brand]['Puissance_maximale_recharge'] %>
  <% if puissance_maximale > capacite_batterie %>
    <% puissance_maximale = capacite_batterie %>
  <% end %>
  <% cout_pour_1_heure = puissance_maximale * 0.22 %>
  <% end %>

  <%# ci dessous affiche les stations ! %>
  <% if @stations != "" %>
  <div class="mt-2 mb-4 p-1 <%= "d-none" if params[:address] == ""%>">

    <div>Stations proche de: <div class="proche-de-lieux"><%= params[:address] %></div></div>

  </div>
    <% @stations.each do |station| %>
    <% barreColor = station.user.xp < 25000 ? "#cad82e" : station.user.xp < 50000 ? "#5ea482" : station.user.xp < 75000 ? "#fecd4f" : "#fe9751"
       mateType = station.user.xp < 25000 ? "Mate Débutant" : station.user.xp < 50000 ? "Mate Avancé" : station.user.xp < 75000 ? "Super Mate" : "Top Mate"
       barreLength = (station.user.xp - ((station.user.xp.to_f / 1000).floor * 1000)) / 10
       userLevel = (station.user.xp.to_f / 1000).floor
       adresse = station.address.length < 15 ? station.address : station.address[0..15] + "..."
       codepostal = " " + station.address.scan(/\d{5}/)[0] if station.address.scan(/\d{5}/)[0]
    %>

      <div class="carte-station-index container-sm mt-3 d-flex flex-column justify-content-center mb-1">
        <div>
          <div class="image-station-index-filter" <% if station.photo.attached? %> style="background-image: url('<%= cl_image_path(station.photo.key, crop: :fill) %>')"<% end %>></div>

          <div class="station-avatar-rond" <% if station.user.photo.attached? %> style="background-image: url('<%= cl_image_path(station.user.photo.key, crop: :fill) %>')"<% end %>></div>
          <div class="d-flex justify-content-between">
            <div class="d-flex flex-column">
              <div class="station-username d-flex align-items-end mt-2"><%= station.user.username.capitalize %> <div class="station-username-level ps-1"><%= userLevel %></div></div>
              <div class="mate-type-station"><%= mateType %></div>

               <% feuille_user = station.user.xp < 25000 ? Badge.f[0] : station.user.xp < 50000 ? Badge.f[1] : station.user.xp < 75000 ? Badge.f[2] : Badge.f[3] %>
              <div class="feuille-stations-show" style="background-image: url('<%= feuille_user%>');"></div>

              <div class="barre-de-niveau-station" style="--width-barre: <%= barreLength%>%; --color-barre: <%= barreColor%>;"></div>

            </div>
            <div class="d-flex flex-column align-items-end">
                <div class="mt-1 disponible-station">Disponible</div>
                <div class="mate-type-station bis"><%= params[:date_available].to_time.strftime("%d-%m-%Y") if params[:date_available] != "" %></div>
                <div class="d-flex justify-content-end prix-green"><%= "%.2f" % (station.max_kW_recharge * 0.23).round(2) %>€/h + 3€ fixe</div>

            </div>
          </div>


        </div>
        <div class="d-flex justify-content-between bouton-reserver-station" data-controller="toggle-address" >


                <div class="d-flex flex-column align-items-end">
                  <%= form_with model: [station, @booking] do |f| %>
                  <%= f.datetime_field :date_heure_reservation, :value => params[:date_available].to_time , class:"d-none"%>
                  <%= f.number_field :vehicle_id, :value => params[:plug], class: "d-none"%>
                  <%= f.submit "Reserver", class:"bouton-station-index-carte text-center border-none" %>
                  <% end %>
                </div>

                <% if station.address.length > 35 %>
                  <div data-toggle-address-target="smalla" data-action="click->toggle-address#toggle" class="station-adresse"><%= adresse + codepostal %></div>
                  <div data-toggle-address-target="biga" data-action="click->toggle-address#toggle" class="station-adresse d-none"><%= station.address %></div>
                  <% else %>
                  <div class="station-adresse"><%= station.address %></div>
                <% end %>

            </div>
      </div>
    <% end %>
  <% end %>
  <div class="mt-5 pt-5"></div>
</div>

app/views/stations/new.html.erb
<div class="container pb-5 mb-5">
<!-- app/views/stations/new.html.erb -->

<div class="container-edit-vehicle py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white form-creation-vehicle p-3 shadow">
        <h3>Nouvelle Station</h3>

        <%= simple_form_for [@user, @station] do |f| %>
          <%= f.input :address, label: 'Adresse' %>
          <%= f.input :comment_supply, label: "Complément d'adresse" %>
          <%= f.input :plug, label: 'Type de prise', collection: ["Type 2", "CSS Combo"] %>
          <%= f.input :brand, label: "Marque" %>
          <%= f.input :model, label: "Modèle" %>
          <%= f.input :max_kW_recharge, label: "Puissance Max (kW) de Recharge"%>
          <%= f.input :available, as: :boolean, label: 'Disponible' %>
          <%= f.input :avaibility_end, as: :date, label: "Date de Fin de Disponibilité" %>
          <%= f.input :code_station, label: "Code de la Station" %>
          <%= f.input :photo, as: :file, label: "Photo" %>

          <div class="btn bouton-creation-voiture">
            <%= f.submit 'Ajouter ma borne de recharge'%>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>