config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check
  root to: "stations#index"

  resources :stations, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    resources :bookings, only: [:create]
  end

  resources :users, only: [:show, :update] do
    resources :vehicles, only: [:new, :create, :edit, :update] # Ressources des véhicules
  end

  get '/leaderboard', to: 'users#leaderboard'
  resources :vehicles, only: [:edit, :update, :destroy, :new, :create]

  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do

    resources :conflicts, only: [:new, :create]
    resources :messages, only: [:create] # Ressource des messages
    member do
      patch :submit_offer
      patch :accept_offer
      patch :reject_offer
      patch :start_charge
      patch :stop_charge
      patch :validate_payment
    end
  end

  resources :vehicles do
    get 'get_models_by_brand', on: :collection
  end


  resources :badges, only: [:create, :destroy]

  get '/wheel', to: 'wheels#index'

  post '/start_reservation', to: 'reservations#start_reservation'
  post '/accept_offer', to: 'reservations#accept_offer'
  post '/reject_offer', to: 'reservations#reject_offer'
  post '/start_charging', to: 'reservations#start_charging'
  post '/stop_charging', to: 'reservations#stop_charging'

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :vehicle
  belongs_to :station
  has_many :messages, dependent: :destroy
  has_many :conflicts, dependent: :destroy
  before_create :set_default_status
  has_one :user, through: :vehicle
  has_one :station_owner, through: :station, source: :user



  enum status: {
    en_attente_de_soumission: 'en_attente_de_soumission',
    en_attente_de_confirmation: 'en_attente_de_confirmation',
    en_attente_de_validation: 'en_attente_de_validation',
    en_attente_de_paiement: 'en_attente_de_paiement',
    en_attente_de_charge: 'en_attente_de_charge',
    en_charge: 'en_charge',
    termine: 'termine'
  }

  def en_attente_de_confirmation?
    status == 'en_attente_de_confirmation'
  end

  def en_attente_de_soumission?
    status == 'en_attente_de_soumission'
  end

  def en_attente_de_validation?
    status == 'en_attente_de_validation'
  end

  def en_attente_de_paiement?
    status == 'en_attente_de_paiement'
  end

  def en_attente_de_charge?
    status == 'en_attente_de_charge'
  end

  def en_charge?
    status == 'en_charge'
  end

  def termine?
    status == 'termine'
  end

  def initier_offre!
    update(status: :en_attente_de_confirmation)
  end

  def confirmer_offre!
    update(status: :en_attente_de_soumission)
  end

  def soumettre_offre!
    update(status: :en_attente_de_validation)
    created_message = messages.create(content: "🤖 Message bot: Bonjour👋, je souhaite venir recharger ma voiture le #{date_heure_reservation.strftime('%d/%m/%Y')} à #{date_heure_reservation.strftime('%H:%M')}.", user: vehicle.user)
    refresh_tchat(created_message)
  end

  def accepter_offre!
    update(status: :en_attente_de_paiement)
    created_message = messages.create(content: "🤖 Message bot: Bonjour👋, votre demande est acceptée. La place est disponible pour le #{date_heure_reservation.strftime('%d/%m/%Y')} à #{date_heure_reservation.strftime('%H:%M')}.", user: station.user)
    refresh_tchat(created_message)
  end

  def refuser_offre!
    update(status: :termine)
    created_message = messages.create(content: "🤖 Message bot: Bonjour, 🫣 oups je ne serais pas disponible.", user: station.user)
    refresh_tchat(created_message)
  end

  def valider_paiement!
    update(status: :en_attente_de_charge)
    message_paiement = messages.create(content: "🤖 Message bot: ✅ Paiement effectué le #{Time.zone.now.strftime('%d/%m/%Y à %H:%M')}", user: vehicle.user)
    message_comment_supply = messages.create(content: "🤖 Message bot: #{station.comment_supply}", user: station.user)
    refresh_tchat(message_paiement)

  end

  def commencer_charge!
    update(status: :en_charge, date_heure_debut_recharge: Time.current)
    created_message = messages.create(content: "🤖 Message bot: 🔌 Mon véhicule est en charge", user: vehicle.user)
    refresh_tchat(created_message)
  end

  def terminer_charge!
    update(status: :termine, date_heure_fin_recharge: Time.current)
    duration = recharge_duration
    kwh = kw_h_consommes_reel
    percentage = pourcentage_batterie_reel
    created_message = messages.create(content: "🤖 Message bot: 🔋 J'ai fini de recharger mon véhicule, j'ai rechargé #{duration} heures, environ #{kwh} kW/h ce qui représente #{percentage}% de ma batterie, Merci ChargeMate!", user: vehicle.user)
    refresh_tchat(created_message)
  end


  def recharge_duration
    return 0 unless date_heure_debut_recharge && date_heure_fin_recharge

    ((date_heure_fin_recharge - date_heure_debut_recharge) / 1.hour).round(2)
  end

  def kw_h_consommes_reel
    puissance_station = station.max_kW_recharge || 0
    puissance_vehicule = vehicle.puissance_maximale_recharge || 0
    puissance_effective = [puissance_station, puissance_vehicule].min
    capacite_batterie = vehicle.capacite_batterie
    energie_potentielle = recharge_duration * puissance_effective
    energie_consommee = [energie_potentielle, capacite_batterie].min
    energie_consommee.round(1)
  end

  def pourcentage_batterie_reel
    capacite_batterie = vehicle.capacite_batterie
    energie_consommee_kwh = kw_h_consommes_reel
    pourcentage = capacite_batterie > 0 ? (energie_consommee_kwh / capacite_batterie.to_f * 100) : 0
    pourcentage.round(1)
  end

  def duree_recharge_heures
    return 0 unless date_heure_fin_de_reservation && date_heure_reservation

    ((date_heure_fin_de_reservation - date_heure_reservation) / 1.hour).round(2)
  end

  def kw_h_consommes_reservation
    puissance_station = station.max_kW_recharge || 0
    puissance_vehicule = vehicle.puissance_maximale_recharge || 0
    puissance_effective = [puissance_station, puissance_vehicule].min
    capacite_batterie = vehicle.capacite_batterie
    energie_potentielle = duree_recharge_heures * puissance_effective
    energie_consommee = [energie_potentielle, capacite_batterie].min
    energie_consommee.round(1)
  end

  def pourcentage_batterie_reservation
    capacite_batterie = vehicle.capacite_batterie
    energie_consommee_kwh = kw_h_consommes_reservation
    pourcentage = capacite_batterie > 0 ? (energie_consommee_kwh / capacite_batterie.to_f * 100) : 0
    pourcentage.round(1)
  end

  def prix_total_recharge
    prix_par_kwh = 0.23
    prix_base_stationnement = 3
    energie_consommee_kwh = kw_h_consommes_reservation
    (energie_consommee_kwh * prix_par_kwh + prix_base_stationnement).round(2)
  end

  private

  def refresh_tchat(message)
    TchatMateChannel.broadcast_to(
      self,
      ApplicationController.render(partial: 'messages/messagelist', locals: { booking: self })
    )
  end

  def set_default_status
    self.status ||= 'en_attente_de_soumission'
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :update, :destroy]
  # , :submit_offer, :accept_offer, :reject_offer, :start_charge, :stop_charge, :validate_payment
  before_action do
    current_user.badges.each do |badge|
      if badge.duration < Time.now
        badge.destroy
      end
    end
  end


  def index
    # Pour récupérer les véhicules et la station de l'utilisateur actuel
    user_vehicles = current_user.vehicles
    user_station = current_user.station
    user_vehicles_ids = Vehicle.where(user_id: params[:user_id]).pluck(:id)
    station_bookings = current_user.station.bookings.where.not(status: 'en_attente_de_confirmation') if current_user.station.present?
    # Pour afficher seulement les bookings reliés aux véhicules et aux stations de l'utilisateur actuel
    if current_user.station
      @bookings = Booking.where(vehicle_id: user_vehicles.ids).or(Booking.where(station_id: user_station.id)).order('created_at DESC')
    else
      @bookings = Booking.where(vehicle_id: user_vehicles.ids).order('created_at DESC')
    end
  end

  def new
    @station = Station.find(params[:station_id])
    @booking = @station.bookings.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.station_id = params[:station_id]

    @booking.status = 'en_attente_de_confirmation'

    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def show
    @message = Message.new
    @is_owner = (current_user == @booking.vehicle.user)
  end

  def update
    @is_owner = (current_user == @booking.vehicle.user)
    check_and_return(@booking)
    case @booking.status
      when "en_attente_de_confirmation" then confirm_offer
      when "en_attente_de_soumission" then submit_offer
      when "en_attente_de_validation" then accept_offer
      when "en_attente_de_paiement" then validate_payment
      when "en_attente_de_charge" then start_charge
      when "en_charge" then stop_charge
    end
    ActionBookingChannel.broadcast_to(
      @booking, {
        owner: render_to_string(partial: "bookings/action_choice", locals: { booking: @booking, is_owner: true } ),
        customer: render_to_string(partial: "bookings/action_choice", locals: { booking: @booking, is_owner: false } ),
        # messages: render_to_string(partial: "messages/message", locals: { booking: @booking }, formats: [:html])

      }
    )

    if @booking.status == "termine"
      #xp
      gain_xp = 300
      if (@booking.station.user.badges.find_by_name("double_xp"))
        gain_xp = gain_xp * 2
      end
      #orders
      @booking.station.user.orders ? u_order = @booking.station.user.orders + 1 : u_order = 1
      ### update @booking.station.user
      @booking.station.user.update(orders: u_order, xp: @booking.station.user.xp + gain_xp )


      (@booking.vehicle.user.seriecurrent - @booking.vehicle.user.seriestart) > 60 * 60 * 24 ? serie = ((@booking.vehicle.user.seriecurrent - @booking.vehicle.user.seriestart) / (60 * 60 * 24 * 7)).ceil : serie = 0
      serie * 100 > 1000 ? serie = 1000 : serie = serie * 100
      gain_xp = serie + 300
      if (@booking.vehicle.user.badges.find_by_name("double_xp"))
        gain_xp = gain_xp * 2
      end
      #orders
      @booking.vehicle.user.orders ? u_order = @booking.vehicle.user.orders + 1 : u_order = 1
      #serie
      if @booking.vehicle.user.seriecurrent + 60 * 60 * 24 * 7 < Time.now && !(@booking.vehicle.user.badges.find_by_name("freeze") || @booking.vehicle.user.badges.find_by_name("freeze_month"))
        u_seriestart = Time.now
        u_seriecurrent = Time.now + 60 * 60 * 24
      else
        u_seriestart = @booking.vehicle.user.seriestart
        u_seriecurrent = Time.now
      end
      ### update @booking.vehicle.user
      @booking.vehicle.user.update(orders: u_order, seriestart: u_seriestart, seriecurrent: u_seriecurrent, xp: @booking.vehicle.user.xp + gain_xp )

      ### gere minusoneeuro
      if @booking.vehicle.user.badges.find_by_name("minus_one_euro")
        @booking.vehicle.user.badges.find_by_name("minus_one_euro").update(created_at: "1999-12-31 23:00:00")
      end
    end
  end

  def destroy
    @booking.destroy
    redirect_to user_path(current_user)
  end

  private



  def check_and_return(booking)
    if booking.status == "en_attente_de_confirmation"
      booking.update(booking_params)
      booking.initier_offre!
      redirect_to booking_path(booking)
      return
    end
  end

  def confirm_offer
    @booking.confirmer_offre!
  end

  def submit_offer
    @booking.soumettre_offre!
  end

  def accept_offer
    @booking.accepter_offre!
  end

  def reject_offer
    @booking.refuser_offre!
  end

  def start_charge
    @booking.commencer_charge!
  end

  def stop_charge
    @booking.terminer_charge!
  end

  def validate_payment
    @booking = Booking.find(params[:id])
  @booking.valider_paiement!
  rescue ActiveRecord::RecordNotFound
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:vehicle_id, :station_id, :date_heure_reservation, :date_heure_fin_de_reservation)
  end
end

app/views/bookings/_action_choice.html.erb
<div class="centrer-les-boutons-style d-flex justify-content-center align-center">
<% if is_owner == true %>
  <%= render 'owner_bookingactions', booking: booking %>
<% else %>
  <%= render 'customer_bookingactions', booking: booking %>
<% end %>
</div>

app/views/bookings/_booking_button.html.erb
  <p><%= button_to message, booking_path(booking), method: :patch %></p>

app/views/bookings/_booking_text.html.erb
<p><%= status %> <%= username %>.</p>

app/views/bookings/_card_customer.html.erb
<div class="carte-index-booking-background-image" <% if booking.station.photo.attached? %> style="background-image: url('<%= cl_image_path(booking.station.photo.key, crop: :fill) %>')"<% end %>> </div>

<div class="carte-index-booking-avatar" <% if booking.vehicle.user.photo.attached? %> style="background-image: url('<%= cl_image_path(booking.vehicle.user.photo.key, crop: :fill) %>')" <% end %>> </div>


      <% feuille_user = booking.vehicle.user.xp < 25000 ? Badge.f[0] : booking.vehicle.user.xp < 50000 ? Badge.f[1] : booking.vehicle.user.xp < 75000 ? Badge.f[2] : Badge.f[3] %>
      <div class="feuille-bookings-show" style="background-image: url('<%= feuille_user%>');"></div>


<div class="date-absolute-booking"><%= booking.created_at.strftime("%d-%m-%Y") %></div>

<%# <i class="fa-brands fa-envira"></i> %>
  <div class="carte-index-booking-content">
    <div class="carte-index-booking-infos">
      <img src="https://i.ibb.co/Rj0NcB2/voiture-de-sport-1.png" class="badge-car-station-booking-prise" alt="plug">
      <%# <h4><%= booking.vehicle.user.username.capitalize </h4> %>

      <%# ci dessous variables PUIS nom, niveau et barre %>
        <%
          userLevel = (booking.vehicle.user.xp.to_f / 1000).floor
        %>

        <div class="d-flex flex-column">
              <div class="station-username d-flex align-items-end ms-3 ps-1"><%= booking.vehicle.user.username.capitalize %> <div class="station-username-level ps-1"><%= userLevel %></div></div>
        </div>

    </div>
    <% bouton_texte = booking.status != "en_attente_de_soumission" && booking.status != "en_attente_de_confirmation" ? "Consulter" : "Reserver" %>
    <%# à remplacer par booking_path(@booking) %>
    <%= link_to bouton_texte, booking_path(booking), class: "btn bouton-index-booking" %>
  </div>

app/views/bookings/_card_owner.html.erb
<div class="carte-index-booking-background-image" <% if booking.station.photo.attached? %> style="background-image: url('<%= cl_image_path(booking.station.photo.key, crop: :fill) %>')"<% end %>></div>

<%# <img src="https://i.ibb.co/vQ5k3GG/Capture-d-cran-2024-02-16-170917.png" alt="" class="carte-index-booking-avatar"> %>

<div class="carte-index-booking-avatar" <% if booking.station.user.photo.attached? %>
  style="background-image: url('<%= cl_image_path(booking.station.user.photo.key, height: 300, crop: :fill) %>')"
<% end %>>
</div>

      <% feuille_user = booking.station.user.xp < 25000 ? Badge.f[0] : booking.station.user.xp < 50000 ? Badge.f[1] : booking.station.user.xp < 75000 ? Badge.f[2] : Badge.f[3] %>
      <div class="feuille-bookings-show" style="background-image: url('<%= feuille_user%>');"></div>


<%# <i class="fa-brands fa-envira"></i> %>
<div class="date-absolute-booking"><%= booking.created_at.strftime("%d-%m-%Y") %></div>
  <div class="carte-index-booking-content">
    <div class="carte-index-booking-infos">
      <img src="https://i.ibb.co/3TcC1Mr/prise-de-courant-1.png" class="badge-car-station-booking" alt="car">
      <%# <h4><%= booking.station.user.username.capitalize </h4> %>

        <%# ci dessous variables PUIS nom, niveau et barre %>
        <%
          userLevel = (booking.station.user.xp.to_f / 1000).floor
        %>

        <div class="d-flex flex-column">
              <div class="station-username d-flex align-items-end ms-3 ps-1"><%= booking.station.user.username.capitalize %> <div class="station-username-level ps-1"><%= userLevel %></div></div>
        </div>


    </div>

    <% bouton_texte = booking.status != "en_attente_de_soumission" && booking.status != "en_attente_de_confirmation" ? "Consulter" : "Reserver" %>
    <%# à remplacer par booking_path(@booking) %>
    <%= link_to bouton_texte, booking_path(booking), class: "btn bouton-index-booking" %>
  </div>

app/views/bookings/_card_owner_new.html.erb
<div class="carte-index-booking-background-image" <% if booking.station.photo.attached? %> style="background-image: url('<%= cl_image_path(booking.station.photo.key, crop: :fill) %>')"<% end %>></div>
<%# <img src="https://i.ibb.co/vQ5k3GG/Capture-d-cran-2024-02-16-170917.png" alt="" class="carte-index-booking-avatar"> %>

<div class="carte-index-booking-avatar" <% if booking.station.user.photo.attached? %>
  style="background-image: url('<%= cl_image_path(booking.station.user.photo.key, height: 300, crop: :fill) %>')"
<% end %>>
</div>

<% feuille_user = booking.station.user.xp < 25000 ? Badge.f[0] : booking.station.user.xp < 50000 ? Badge.f[1] : booking.station.user.xp < 75000 ? Badge.f[2] : Badge.f[3] %>
      <div class="feuille-bookings-show" style="background-image: url('<%= feuille_user%>');"></div>

<%# <i class="fa-brands fa-envira"></i> %>
<div class="date-absolute-booking"></div>

  <div class="carte-index-booking-content">
    <div class="carte-index-booking-infos">
      <img src="https://i.ibb.co/3TcC1Mr/prise-de-courant-1.png" class="badge-car-station-booking" alt="car">
      <%# <h4><%= booking.station.user.username.capitalize </h4> %>

        <%# ci dessous variables PUIS nom, niveau et barre %>
        <%
          userLevel = (booking.station.user.xp.to_f / 1000).floor
        %>

        <div class="d-flex flex-column">
      <div class="station-username d-flex align-items-end ms-3 ps-1">
        <%= booking.station.user.username.capitalize %>
        <div class="station-username-level ps-1"><%= userLevel %></div>
      </div>
    </div>
  </div>

</div>
  <div class="reservation ">
    <%= form_with model: booking, url: booking_path(booking), method: :patch, class: "reservation-form" do |form| %>
      <div class="d-flex flex-column mb-2 text-secondary">
        <%= form.label :date_heure_reservation, "Début réservation", class: "ms-2" %>
        <%= form.datetime_field :date_heure_reservation, class: 'form-control', required: true  %>

        <%= form.label :date_heure_fin_de_reservation, "Fin de réservation", class: "ms-2" %>
        <%= form.datetime_field :date_heure_fin_de_reservation, class: 'form-control', required: true  %>
      </div>

      <% bouton_texte = booking.status != "en_attente_de_soumission" && booking.status != "en_attente_de_confirmation" ? "Consulter" : "Reserver" %>
      <p class="bouton-reserver"><%= form.submit bouton_texte, class: "btn bouton-index-booking" %></p>
    <% end %>
  </div>

app/views/bookings/show.html.erb
<!-- Header -->
<div class="bookinghead">
  <!-- Header vignette photo garage -->

   <div class="bookingbackgroud text-white" <% if @booking.station.photo.attached? %> style="background-image: url('<%= cl_image_path(@booking.station.photo.key, crop: :fill) %>')" <% end %>></div>






<% if @booking.station.user_id == current_user.id %>
  <!-- Header photo du locataire de la borne -->
  <div class="bookingheadpic" <% if @booking.vehicle.user.photo.attached? %> style="background-image: url('<%= cl_image_path(@booking.vehicle.user.photo.key, crop: :fill) %>')" <% end %>>
    <!-- Header username du locataire de la borne -->
    <div class="bookingheadusername">

    <%userLevel = (@booking.vehicle.user.xp.to_f / 1000).floor%>

          <% feuille_user = @booking.vehicle.user.xp < 25000 ? Badge.f[0] : @booking.vehicle.user.xp < 50000 ? Badge.f[1] : @booking.vehicle.user.xp < 75000 ? Badge.f[2] : Badge.f[3] %>
            <div class="feuille-bookings-show-profile" style="background-image: url('<%= feuille_user%>');"></div>
       <div class="station-username d-flex align-items-end"><%= @booking.vehicle.user.username.capitalize %> <div class="station-username-level ps-1"><%= userLevel %></div></div>

      <!-- Header des logos map et waze -->
      <div class="bookingwaze"></div>
    </div>
  </div>
<% else %>
 <!-- Header photo du locataire de la borne -->
  <div class="bookingheadpic" <% if @booking.station.user.photo.attached? %> style="background-image: url('<%= cl_image_path(@booking.station.user.photo.key, crop: :fill) %>')" <% end %>>
    <!-- Header username du locataire de la borne -->
    <div class="bookingheadusername">

    <%userLevel = (@booking.station.user.xp.to_f / 1000).floor%>

            <% feuille_user = @booking.station.user.xp < 25000 ? Badge.f[0] : @booking.station.user.xp < 50000 ? Badge.f[1] : @booking.station.user.xp < 75000 ? Badge.f[2] : Badge.f[3] %>
            <div class="feuille-bookings-show-profile" style="background-image: url('<%= feuille_user%>');"></div>

       <div class="station-username d-flex align-items-end"><%= @booking.station.user.username.capitalize %> <div class="station-username-level ps-1"><%= userLevel %></div></div>

      <!-- Header des logos map et waze -->
      <div class="bookingwaze"></div>
    </div>
  </div>
<% end %>








</div>

<div class="barregrise"></div>

<!-- details du contrat entre les deux parties-->
<div class="bookingdetail">
  <!-- marque/modele de la voiture   -->
  <div class="cardisplay mb-4">
    <div class="brandmodel card-text d-flex justify-content-center align-items-center">
      <%= image_tag @booking.vehicle.car_list[@booking.vehicle.brand]['Logo_url'], alt: "Vehicle Logo", width: "30px" %>
      <span class="mx-1"></span><%= @booking.vehicle.brand %> <%= @booking.vehicle.model %>
    </div>
    <div class="plugtype d-flex justify-content-center align-items-center">
      <%= @booking.vehicle.plug %> <span class="mx-1"></span><%= image_tag @booking.vehicle.car_list[@booking.vehicle.brand]['Logo_prise_url'], alt: "prise Logo", width: "25px" %>
    </div>
  </div>

  <!-- div reservationcontainer -->
    <h5 class="titre-votre-reservation d-flex justify-content-center">Détails de la réservation</h5>
  <div class="reservationcontainer d-flex flex-wrap justify-content-center mb-4">
  <!-- div date-heure-reservation -->
  <div class="date-heure-reservation">
    <!-- div date debut de reservation -->
    <div class="date-heure-reservationcard">Date début de réservation
      <p><%= @booking.date_heure_reservation.strftime("%d/%m/%Y") %> à <%= @booking.date_heure_reservation.strftime("%H:%M")%> </p>
    </div>
    <!-- div date fin de reservation -->
    <div class="date-heure-reservationcard">Date fin de réservation
      <p><%= @booking.date_heure_fin_de_reservation.strftime("%d/%m/%Y") %> à <%=@booking.date_heure_fin_de_reservation.strftime("%H:%M")  %></p>

    </div>
  </div><!-- fin date-heure-reservation  -->

  <!-- div recap reservation details € kw/h temps % -->
  <div class= "detailscontainer">

    <!-- div temps  -->
    <div class="details-reservationcard">
      <p class="titre-reservation-details">Temps</p>
      <p><%= @booking.duree_recharge_heures %> h</p>
    </div> <!-- fin prix details-reservationcard   -->
    <!-- div kw/h -->
    <div class="details-reservationcard">
      <p class="titre-reservation-details">Charge</p>
      <p class="smaller"><%= @booking.kw_h_consommes_reservation %>kW/h</p>
    </div> <!-- fin prix details-reservationcard   -->


    <!-- div % -->
    <div class="details-reservationcard">
      <p class="titre-reservation-details">Batterie</p>
      <p>+<%= @booking.pourcentage_batterie_reservation %>%</p>
    </div> <!-- fin prix details-reservationcard   -->


    <!-- div prix % -->
    <div class="details-reservationcard rose-case">
      <p class="titre-reservation-details">Total</p>
      <p><%= @booking.vehicle.user == current_user && (current_user.badges.find_by_name("minus_one_euro") && current_user.badges.find_by_name("minus_one_euro").created_at != Time.new(2000/01/01) ) ? @booking.prix_total_recharge.to_s + " -1€" : @booking.prix_total_recharge.to_s + " €" %> </p>
    </div> <!-- fin prix details-reservationcard   -->
 </div><!-- fin reservationcontainer  -->
</div>
<div id="mon_xp">Commande terminée !</div>
<div class="barregrise"></div>

<!-- Bouton d'action en fonction des utilisateurs -->
                                                      <!-- Booking action user debut -->
<div class="bookingactionuser"
  data-controller="action-booking"
  data-action-booking-booking-id-value="<%= @booking.id %>"
  data-action-booking-is-owner-value="<%= current_user.id == @booking.vehicle.user.id ? "owner" : "customer" %>"
  data-action-booking-target = "action">

  <%= render "bookings/action_choice", booking: @booking, is_owner: @is_owner %>
</div>                                                  <!-- Booking action user fin -->


<!-- TCHAT -->
<div class="bookingchatroom">


  <!-- Tchatbox -->
  <div class="bookingmessage"
    data-controller="tchatmate-subscription"
    data-tchatmate-subscription-booking-id-value="<%= @booking.id %>">

    <div class="zonetext mt-2"
    data-tchatmate-subscription-target="zonetext">
      <div class="pas-encore-de-message <%= "d-none" if @booking.messages.length > 0%>">Pas encore de message</div>
        <div data-tchatmate-subscription-target="messages">
          <%= render "messages/messagelist", booking: @booking %>
        </div><!-- fin de ma data target messages -->
    </div><!-- fin de zonetext -->



          <!-- ligne input du message -->
          <div class="bookingwhrite">
            <%= simple_form_for [@booking, @message], html: { data: { action: "turbo:submit-end->tchatmate-subscription#resetForm" }, class: "d-flex" } do |f| %>
            <%= f.input :content, label: false, placeholder: "Votre message", wrapper_html: {class: "flex-grow-1"} %>
            <%= f.submit "Envoyer", class: "envoyer btn btn-primary mb-3" %>
            <% end %>
          </div>







  </div><!-- fin de bookingmessage -->
</div><!-- fin de bookingchatroom -->

<!-- Bouton signaler du bas de page -->
<div class="bookingfoot d-flex justify-content-between">
  <!-- Bouton Signaler -->
  <div class="bookingsignalement d-flex justify-content-center align-items-center">
    <%= link_to "SIGNALER", new_booking_conflict_path(@booking), class: "bouton-signaler" %>
  </div>
</div>

<div class=navbarspace></div>