config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check
  root to: "stations#index"

  resources :stations, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    resources :bookings, only: [:create]
  end

  resources :users, only: [:show, :update] do
    resources :vehicles, only: [:new, :create, :edit, :update] # Ressources des véhicules
  end

  get '/leaderboard', to: 'users#leaderboard'
  resources :vehicles, only: [:edit, :update, :destroy, :new, :create]

  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do

    resources :conflicts, only: [:new, :create]
    resources :messages, only: [:create] # Ressource des messages
    member do
      patch :submit_offer
      patch :accept_offer
      patch :reject_offer
      patch :start_charge
      patch :stop_charge
      patch :validate_payment
    end
  end

  resources :vehicles do
    get 'get_models_by_brand', on: :collection
  end


  resources :badges, only: [:create, :destroy]

  get '/wheel', to: 'wheels#index'

  post '/start_reservation', to: 'reservations#start_reservation'
  post '/accept_offer', to: 'reservations#accept_offer'
  post '/reject_offer', to: 'reservations#reject_offer'
  post '/start_charging', to: 'reservations#start_charging'
  post '/stop_charging', to: 'reservations#stop_charging'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChargeMates</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">


    <style>

      <%= ".msg-#{current_user&.id}" %> {

      }


      <%= ".cont-#{current_user&.id}" %> {
          display: flex;
          justify-content: flex-end;
            .message-content {
                  display: flex;
                  justify-content: flex-end;
            }
      }
    </style>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>

  <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  <%= render 'shared/ios_pwa_links' %>
  </head>


  <body>



<%# images pre chargees %>
<img id="2xp" src="https://i.ibb.co/vmLBNRb/2xp.png" alt="" class="d-none">
<img id="cristal" src="https://i.ibb.co/ySR293h/cristal.png" alt="" class="d-none">
<img id="freeze" src="https://i.ibb.co/4TZ6ZHC/freeze.png" alt="" class="d-none">
<img id="freezem" src="https://i.ibb.co/x6D3pWX/freeze-month.png" alt="" class="d-none">
<img id="lv1" src="https://i.ibb.co/BBmhSgS/lv1.png" alt="" class="d-none">
<img id="bonuse" src="https://i.ibb.co/GsJnyG0/moin-euro.png" alt="" class="d-none">
<img id="sp_week" src="https://i.ibb.co/HTW0v1G/weekly-sp.png" alt="" class="d-none">
<img id="noneb" src="https://i.ibb.co/whmjwTt/fail.png" alt="" class="d-none">



<div data-controller="preloader" data-preloader-target="introscreen" data-action="click->preloader#getout" class="preloader d-flex flex-column justify-content-center align-items-center
<%= "d-none" if request.original_url != "https://www.chargemates.xyz/"%>">
<div class="logo-center"></div>
<div>ChargeMates</div></div>


<%= render "shared/flashes" %>

<div class="navbarre d-flex justify-content-around align-items-center">
  <div class="d-flex flex-column align-items-center justify-content-center pt-2">
    <%= link_to root_path do %>
    <i class="navbarre-icon fa-solid fa-magnifying-glass" style="font-size: 1.2rem;"></i>
    <% end %>
    <div>Rechercher</div>
  </div>
  <div class="d-flex flex-column align-items-center justify-content-center pt-2">
    <%= link_to user_path(current_user ? current_user : 1) do %>
    <i class="navbarre-icon fa-solid fa-user" style="font-size: 1.2rem;"></i>
    <% end %>
    <div>Mon profil</div>
  </div>
  <div class="d-flex flex-column align-items-center justify-content-center pt-2">
    <%= link_to bookings_path do %>
    <i class="navbarre-icon fa-solid fa-users" style="font-size: 1.2rem;"></i>
    <div id="notif-b" class="notification-blue d-flex justify-content-center align-items-center <%= "d-none" unless current_user.station.bookings.last.status == "en_attente_de_validation"%>">1</div>
    <% end %>
    <div>Mes mates</div>
  </div>
  <div class="d-flex flex-column align-items-center justify-content-center pt-2">
  <%= link_to '/wheel' do %>
    <i class="navbarre-icon fa-solid fa-dice" style="font-size: 1.2rem;"></i>
    <% end %>
    <% if current_user %>
      <div class="notification-red d-flex justify-content-center align-items-center <%= "d-none" if current_user.wheel > Time.now - 60 * 60 * 24%>">1</div>

    <% end %>
    <div>Tente ta chance</div>
  </div>
</div>


    <%= yield %>
  </body>
</html>